### ISSUE TITLE
Capture the top-level project in the Maven extension

### ISSUE THREAD

**Issue by wilkinsona** [spring-io/gradle-enterprise-conventions#15]
We could do something similar to https://github.com/gradle/gradle-enterprise-build-config-samples/pull/30 so that we capture the top-level project (as specified with `-f`) in a custom value that's attached to the build scan.

**Comment by ascheman** [comment]
Not sure if this applies here (@marcphilipp invited me to join the discussion): We do have typical builds with `mvn -am -pl <project list>`: Several modules from a multi-module build would be build then including their dependent modules. For this case it would be hard to derive a proper project name. In multi-module builds we do have many entries in the scan list, all with the same top level project name. From my point of view a custom name would be great (e.g., something like `-Dscan.build.name=...`).

**Comment by wilkinsona** [comment]
That's an interesting problem, but out of scope for these extensions as we (the Spring team) don't have any Maven-based builds where we use `-pl <project list>`.

**Comment by ascheman** [comment]
Thanks, addressed this directly to Gradle: gradle/gradle-enterprise-build-config-samples#32

**Comment by wilkinsona** [comment]
We're no longer using Gradle Enterprise with Maven.
