### ISSUE TITLE
Allow scans to be published to scans.gradle.com when authenticating with ge.spring.io isn't possible

### ISSUE THREAD

**Issue by wilkinsona** [spring-io/gradle-enterprise-conventions#16]
The Spring Security team would like to publish build scans from pull request builds. ge.spring.io cannot be used for that as it does not support anonymous publication and we don't want to expose the credentials. It would be useful if the conventions for publication (publishing to ge.spring.io, requiring authentication, etc) backed off and used Gradle's defaults when a build is run with `--scan`.

**Comment by etiennestuder** [comment]
Cool idea.
