### ISSUE TITLE
Apply build cache conventions when using Maven

### ISSUE THREAD

**Issue by wilkinsona** [spring-io/gradle-enterprise-conventions#17]
Gradle Enterprise Extension 1.6.5 has added support for programmatic configuration of the build cache. This allows us to more closely align the Maven conventions with the Gradle conventions and will allow Maven projects that use the conventions to simplify their gradle-enterprise.xml configuration.

**Comment by etiennestuder** [comment]
See https://github.com/gradle/gradle-enterprise-build-config-samples/blob/master/common-custom-user-data-maven-extension/src/main/java/com/gradle/CommonCustomUserDataMavenExtension.java#L37-L42 for how to access the new BuildCacheApi.

**Comment by etiennestuder** [comment]
Cool!
