### ISSUE TITLE
Consider supporting multiple toolchains in JDK tags or custom values

### ISSUE THREAD

**Issue by sbrannen** [spring-io/gradle-enterprise-conventions#30]
This is a follow-up to #22.

The Spring Framework build supports two toolchain versions configured via project properties named `mainToolchain` and `testToolchain`; whereas, #22 introduced support for a single project property named `toolchainVersion`.

This issue aims to address the following.

- Decide on a mechanism for specifying a toolchain version property named something other than `toolchainVersion`.
- Decide if multiple toolchains should be supported.
  - if so, how many?
  - if so, how would they be named/discovered?
- Decide what format or naming convention to use to differentiate between the toolchains in the generated tags or custom values.
- Decide if such information should be included as _tags_ or _custom values_.

**Comment by wilkinsona** [comment]
I went looking for some examples of Framework's scans using the main and test toolchains and couldn't find anything recent. [The latest builds that are available at the moment](https://ge.spring.io/scans?search.names=Main%20toolchain&search.relativeStartTime=P90D&search.timeZoneId=Europe/London&search.values=*) are a couple of months old. Is this still needed? Even if it is, it feels like something that's quite project-specific and I'm not convinced that it should be made a convention at this time.

**Comment by wilkinsona** [comment]
The doesn't appear to have been much demand for this and it still feels project-specific to me. If this is still needed, I think it should be handled in Framework's build.
