### ISSUE TITLE
Conditional publishing

### ISSUE THREAD

**Issue by jonatan-ivanov** [spring-io/gradle-enterprise-conventions#33]
It seems the plugin does not let users to conditionally enable/disable publishing the build scan: see [`configurePublishing`](https://github.com/spring-io/gradle-enterprise-conventions/blob/main/src/main/java/io/spring/ge/conventions/gradle/BuildScanConventions.java#L79-L88).

I would like to disable publishing using an environment variable, e.g.: if I want to play with something in my build script that would pollute the ge server, it would be great if I could disable build scans for all of the subsequent builds (by using an env var). The Gradle Enterprise Plugin has a feature for this (`publishAlwaysIf`) but if I try to use it:

```groovy
gradleEnterprise {
    buildScan {
        // export ORG_GRADLE_PROJECT_PUBLISH_BUILD_SCAN=false
        publishAlwaysIf(Boolean.valueOf(System.env.'ORG_GRADLE_PROJECT_PUBLISH_BUILD_SCAN' ?: true))
    }
}
```

It does not work I guess because `buildScan.publishAlways();` is called.
Instead of calling `publishAlways`, would it make sense to make build scanning an opt-out feature?

The workaround right now is messing with the credentials (wiping or moving the credentials file).

**Comment by wilkinsona** [comment]
I’m sure we can come up with something.

In the meantime, have you considered using `--no-scan` on the command line? It’s not an environment variable but I find it works pretty well for me.

**Comment by jonatan-ivanov** [comment]
Since I want to turn this off for a longer time (trial and error builds), `--no-scan` is not very convenient since I need to add it to every command, that's why I move the credentials file so that the plugin is unable to publish.

**Comment by wilkinsona** [comment]
Shell history and/or an alias both work pretty well for me without adding complexity here. Have you considered either of those?

**Comment by jonatan-ivanov** [comment]
Yepp, I was thinking about adding a new alias/function to conditionally add `--no-scan` but since I'm not sort on gradle aliases and I wanted to add `gradle-build-scan-enable` and `gradle-build-scan-disable` anyways, I solved it without the extra step (which I agree might be worth it).

**Comment by jonatan-ivanov** [comment]
I looked into using an alias and I think there could be two issues with it:
1. It can conflict with other aliases (e.g.: oh-my-zsh gradle plugin)
2. Can be problematic from the IDE (IntelliJ is running gradle tasks by default)

What do you think about doing something like:
```groovy
publishAlwaysIf(Boolean.valueOf(System.env.'ORG_GRADLE_PROJECT_PUBLISH_BUILD_SCAN' ?: true))
```
instead of
```groovy
buildScan.publishAlways();
```

**Comment by wilkinsona** [comment]
Thinking about this some more, it occurred to me that it's already possible with some small changes to your `settings.gradle` file:

```
plugins {
	id "com.gradle.enterprise" version "3.6.1"
	id "io.spring.ge.conventions" version "0.0.7" apply false
}

settings.startParameter.noBuildScan = true // any logic you want to disable the build scan

apply plugin: 'io.spring.ge.conventions'
```

In light of this, I'm not keen on making any changes to this plugin. Even without this capability I'm not entirely sold on the idea. The 90-day (I think) retention policy and Gradle Enterprise's filtering support makes any pollution a non-issue in my experience. Furthermore, accidentally publishing a build scan when you didn't need one is preferable to accidentally not publishing one when you did so I'm not sure that this logic is something that we should encourage as a convention.
