### ISSUE TITLE
Use develocity.server for the cache server by default

### ISSUE THREAD

**Issue by jonatan-ivanov** [spring-io/gradle-enterprise-conventions#78]
Right now by default, https://ge.spring.io is used as the remote cache server, the url is hard-coded. Would it be possible/make sense to reuse the value of `develocity.server` by default so that if one wants to override it and they don't use a different cache server, they only need to do it in one place?

**Comment by wilkinsona** [comment]
I think it makes sense. Looking at [the javadoc](https://docs.gradle.com/develocity/gradle-plugin/api/com/gradle/develocity/agent/gradle/buildcache/DevelocityBuildCache.html), it sounds like we can leave the server as `null` and it will automatically use the value of `develocity.server`.

**Comment by wilkinsona** [comment]
I was too hasty here and this is harder than I had thought it would be.

By not setting the cache server, building with `--no-scan` no longer works. This should disable build scans but still use the cache. To disable build scans, `develocity.server` is not set. This then requires the build cache's server to be set for the cache to work. If it isn't set, the build fails with "Cannot use Develocity build cache client without specifying Develocity server address".

We also have a similar requirement for `--scan` that should publish an anonymous scan to `scans.gradle.com` while still making use of the build cache. This also doesn't work with this change in place as there's no server configured for the build cache.

To meet the goal of having to only configure the server in one place, we would have to change the current behaviour of `--no-scan` and `--scan` and, unfortunately, I don't think we should do that as it's useful both for core maintainers and contributors.

Sorry, @jonatan-ivanov. I think we'll have to decline this one as I can't see a way to meet all the requirements.

**Comment by jonatan-ivanov** [comment]
No worries, I was afraid of this is not possible or too hard to make sense doing it.
I guess if someone configures the cache first then scan, this can be also problematic.
Thank you!
